name: kubeflow
author: maik bialas
description: compiles a pipelines file and upload it to kubeflow
inputs:
  file:
    description: "python file which describes the pipline"
    required: true
  pipline-service-endpoint:
    description: "api-server url or ip"
    required: true
  pipeline-name:
    description: "name of uploaded pipline"
    required: true
outputs:
  status:
      description: "name of pipline in kubeflow" 
runs:
  using: "node12"
  main: "dist/index.js"