env:
  python-file: 'sequential.py'
  pipline-service-endpoint: 'http://pipelines.bialas.ddnss.org'
  pipline-name: 'sequential'

on: push
jobs:
  kubeflow-upload:
    runs-on: ubuntu-latest
    container: mabi/kubeflowaction:latest
    steps:
      - uses: actions/checkout@v2 

      - name: compile-file
        shell: sh
        run: |
          dsl-compile --py ${{ env.python-file }} --output ${{ env.python-file }}.tar.gz
          
      - uses: ./.github/actions/run_in_kubeflow
        id: kubeflow
        with:
          file: ${{ env.python-file }}.tar.gz
          pipline-service-endpoint: ${{ env.pipline-service-endpoint }}
          pipline-name: ${{ env.pipline-name }}

      - name: get-ouputs
        shell: sh
        run: |
         echo "Pipline: ${{ steps.kubeflow.outputs.pipeline-name }}"


